package view;

import javax.swing.JFrame;

public class Home_GiaoVien extends javax.swing.JFrame {

    public Home_GiaoVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtPhong = new javax.swing.JButton();
        jbtMonHoc = new javax.swing.JButton();
        jbtLop = new javax.swing.JButton();
        jbtDangKy = new javax.swing.JButton();
        btDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 255, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_home_black_24dp.png"))); // NOI18N
        jLabel1.setText("Đăng ký lịch thực hành");

        jbtPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_school_black_24dp.png"))); // NOI18N
        jbtPhong.setText("Phòng học");
        jbtPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPhongActionPerformed(evt);
            }
        });

        jbtMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_auto_stories_black_24dp.png"))); // NOI18N
        jbtMonHoc.setText("Môn học");
        jbtMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMonHocActionPerformed(evt);
            }
        });

        jbtLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_class_black_24dp.png"))); // NOI18N
        jbtLop.setText("Lớp học");
        jbtLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLopActionPerformed(evt);
            }
        });

        jbtDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_app_registration_black_24dp.png"))); // NOI18N
        jbtDangKy.setText("Đăng ký lịch thực hành");
        jbtDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDangKyActionPerformed(evt);
            }
        });

        btDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/outline_logout_black_24dp.png"))); // NOI18N
        btDangXuat.setText("Đăng xuất");
        btDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jbtMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jbtLop, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jbtDangKy)
                        .addGap(18, 18, 18)
                        .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtLop, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChuyenMan(JFrame tenJframe) {
        tenJframe.setVisible(true);
        this.setVisible(false);
    }

    private void jbtPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPhongActionPerformed
        ChuyenMan(new Phong_GiaoVien());

    }//GEN-LAST:event_jbtPhongActionPerformed

    private void jbtMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMonHocActionPerformed
        ChuyenMan(new MonHoc_GiaoVien());
    }//GEN-LAST:event_jbtMonHocActionPerformed

    private void jbtLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLopActionPerformed
        ChuyenMan(new Lop_GV());
    }//GEN-LAST:event_jbtLopActionPerformed

    private void jbtDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDangKyActionPerformed
        ChuyenMan(new GV_DangKyTH());
    }//GEN-LAST:event_jbtDangKyActionPerformed

    private void btDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangXuatActionPerformed
        ChuyenMan(new DangNhap_F());
    }//GEN-LAST:event_btDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_GiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_GiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_GiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_GiaoVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-follbMaGVd>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_GiaoVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangXuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtDangKy;
    private javax.swing.JButton jbtLop;
    private javax.swing.JButton jbtMonHoc;
    private javax.swing.JButton jbtPhong;
    // End of variables declaration//GEN-END:variables
}
